[build]
builder = "nixpacks"
buildCommand = "npx prisma generate"

[deploy]
startCommand = "npx prisma migrate deploy && node api/server.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
